use std::sync::Arc;

use async_trait::async_trait;
use rusty_venture_core::{action::Action, context::ExecutionContext, CoreError};
use rusty_venture_vcs::{FileCommit, RepoProvider, RepoRef};
use serde::{Deserialize, Serialize};
use tracing::{info, warn};

use crate::{
    containerize::{ContainerizeResult, CTX_CONTAINERIZE_RESULT},
    governance::{GovernanceFile, CTX_GOVERNANCE_FILES},
};

pub const CTX_COMMITTED_BRANCHES: &str = "improve.committed_branches";

/// A branch that was created and committed to.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CommittedBranch {
    pub branch_name: String,
    pub commit_sha: String,
    pub files_changed: Vec<String>,
    pub description: String,
}

/// Collects all generated files from context, groups them into branches
/// (independent changes get their own branch; interdependent ones share one),
/// and commits each group via the VCS provider.
///
/// Branch naming: `rusty-venture/<action-group>/<run_id_short>`.
pub struct CreateBranchAction {
    provider: Arc<dyn RepoProvider>,
    repo_owner: String,
    repo_name: String,
    base_branch: String,
}

impl CreateBranchAction {
    pub fn new(
        provider: Arc<dyn RepoProvider>,
        repo_owner: impl Into<String>,
        repo_name: impl Into<String>,
        base_branch: impl Into<String>,
    ) -> Self {
        Self {
            provider,
            repo_owner: repo_owner.into(),
            repo_name: repo_name.into(),
            base_branch: base_branch.into(),
        }
    }
}

#[async_trait]
impl Action for CreateBranchAction {
    type Input = ();
    type Output = Vec<CommittedBranch>;

    fn name(&self) -> &str {
        "create-branch"
    }

    async fn execute(
        &self,
        ctx: &ExecutionContext,
        _input: (),
    ) -> Result<Vec<CommittedBranch>, CoreError> {
        let repo = RepoRef::new(&self.repo_owner, &self.repo_name);
        let run_short = &ctx.run_id.to_string()[..8];
        let mut committed: Vec<CommittedBranch> = vec![];

        // ── Group 1: Governance files (independent, one branch) ───────────
        let governance_files: Option<Vec<GovernanceFile>> =
            ctx.get::<Vec<GovernanceFile>>(CTX_GOVERNANCE_FILES).await;

        if let Some(files) = governance_files {
            if !files.is_empty() {
                let branch = format!("rusty-venture/governance/{run_short}");
                let file_commits: Vec<FileCommit> = files
                    .iter()
                    .map(|f| FileCommit::create(&f.path, &f.content))
                    .collect();
                let paths: Vec<String> = file_commits.iter().map(|f| f.path.clone()).collect();

                match commit_group(
                    &self.provider,
                    &repo,
                    &self.base_branch,
                    &branch,
                    file_commits,
                    "chore: add governance files via rusty-venture",
                )
                .await
                {
                    Ok(sha) => {
                        info!(branch = %branch, files = paths.len(), "Governance branch committed");
                        committed.push(CommittedBranch {
                            branch_name: branch,
                            commit_sha: sha,
                            files_changed: paths,
                            description:
                                "Governance files: LICENSE, SECURITY.md, CONTRIBUTING.md, etc."
                                    .to_string(),
                        });
                    }
                    Err(e) => {
                        warn!(branch = %branch, error = %e, "Failed to commit governance branch")
                    }
                }
            }
        }

        // ── Group 2: Containerization (independent branch) ────────────────
        let containerize: Option<ContainerizeResult> =
            ctx.get::<ContainerizeResult>(CTX_CONTAINERIZE_RESULT).await;

        if let Some(result) = containerize {
            let branch = format!("rusty-venture/containerize/{run_short}");
            let mut file_commits = vec![FileCommit::create(
                &result.dockerfile_path,
                &result.dockerfile_content,
            )];
            let mut paths = vec![result.dockerfile_path.clone()];

            if let Some(compose) = result.compose_content {
                file_commits.push(FileCommit::create("docker-compose.yml", compose));
                paths.push("docker-compose.yml".to_string());
            }

            let validation_note = if result.build_validated {
                "Dockerfile validated with docker build"
            } else {
                "Dockerfile generated but build validation failed — manual review recommended"
            };

            let message = format!(
                "feat: add Dockerfile and docker-compose.yml\n\n{validation_note}\nGenerated by rusty-venture in {} LLM iteration(s).",
                result.fix_iterations + 1
            );

            match commit_group(
                &self.provider,
                &repo,
                &self.base_branch,
                &branch,
                file_commits,
                &message,
            )
            .await
            {
                Ok(sha) => {
                    info!(branch = %branch, files = paths.len(), validated = result.build_validated, "Containerize branch committed");
                    committed.push(CommittedBranch {
                        branch_name: branch,
                        commit_sha: sha,
                        files_changed: paths,
                        description: format!(
                            "Containerization: Dockerfile + docker-compose.yml (validated: {})",
                            result.build_validated
                        ),
                    });
                }
                Err(e) => {
                    warn!(branch = %branch, error = %e, "Failed to commit containerize branch")
                }
            }
        }

        info!(branches = committed.len(), "Branch creation complete");
        ctx.insert(CTX_COMMITTED_BRANCHES, committed.clone()).await;
        Ok(committed)
    }
}

// ── Helper ────────────────────────────────────────────────────────────────────

async fn commit_group(
    provider: &Arc<dyn RepoProvider>,
    repo: &RepoRef,
    base_branch: &str,
    new_branch: &str,
    files: Vec<FileCommit>,
    message: &str,
) -> Result<String, crate::ImprovError> {
    provider
        .create_branch(repo, new_branch, base_branch)
        .await
        .map_err(crate::ImprovError::Vcs)?;

    let sha = provider
        .commit_files(repo, new_branch, files, message)
        .await
        .map_err(crate::ImprovError::Vcs)?;

    Ok(sha.0)
}
